swagger: '2.0'
info:
  description: In-Track - REST Endpoints
  version: 1.0.0
  title: In-Track
basePath: /in-track/
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /v1/sheets/list:
    get:
      tags:
        - CRUD Operations
      summary: ''
      description: ''
      operationId: "getSheetsList"
      parameters:
        - name: url
          in: query
          description: The product id we need to check inventory for
          required: false
          type: string
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/SheetList'
        500:
          description: "Used for a 500 HTTP response - Internal server error"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Used for a 500 HTTP response - Internal server error"
          schema:
            $ref: "#/definitions/Error"
  /v1/sheets/{sheetId}:
    get:
      tags:
        - CRUD Operations
      summary: ''
      description: ''
      operationId: "getSheetData"
      parameters:
        - name: "sheetId"
          in: "path"
          description: "The product id we need to check inventory for"
          required: true
          type: "string"
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/SheetDetails'
        401:
          description: "Used for a 401 HTTP response - Client not authenticated"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "The logged-in user is not permitted to perform the current\
            \ operation."
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Used for a 500 HTTP response - Internal server error"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Used for a 500 HTTP response - Internal server error"
          schema:
            $ref: "#/definitions/Error"
    put:
      tags:
      - CRUD Operations
      summary: "Update the sheet"
      description: "Allows you to update the sheet"
      operationId: "updatePaymentMethod"
      parameters:
      - name: "token"
        in: "header"
        description: "The user's session identifier"
        required: false
        type: "string"
        format: "string"
      - name: "sheetId"
        in: "path"
        description: "The product id we need to check inventory for"
        required: true
        type: "string"
      - in: "body"
        name: "updateSheetInfo"
        description: "The credit card update data"
        required: true
        schema:
          $ref: "#/definitions/SheetDetails"
      responses:
        200:
          description: "A response describing status of the payment method update"
          schema:
            $ref: "#/definitions/TokenAcceptanceResponse"
        401:
          description: "Used for a 401 HTTP response - Client not authenticated"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "The logged-in user is not permitted to perform the current\
            \ operation."
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Used for a 500 HTTP response - Internal server error"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Used for a 500 HTTP response - Internal server error"
          schema:
            $ref: "#/definitions/Error"
    post:
      tags:
      - CRUD Operations
      summary: "Create sheet"
      description: "Allows you to create a new sheet"
      operationId: "createSheetInfo"
      parameters:
      - name: "token"
        in: "header"
        description: "The user's session identifier"
        required: false
        type: "string"
        format: "string"
      - name: "sheetId"
        in: "path"
        description: "The product id we need to check inventory for"
        required: true
        type: "string"
      - in: "body"
        name: "sheetUpdate"
        description: "The sheet update data"
        required: true
        schema:
          $ref: "#/definitions/SheetDetails"
      responses:
        200:
          description: "A response describing status of the payment method update"
          schema:
            $ref: "#/definitions/TokenAcceptanceResponse"
        401:
          description: "Used for a 401 HTTP response - Client not authenticated"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "The logged-in user is not permitted to perform the current\
            \ operation."
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Used for a 500 HTTP response - Internal server error"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Used for a 500 HTTP response - Internal server error"
          schema:
            $ref: "#/definitions/Error"
    delete:
      tags:
      - CRUD Operations
      summary: "delete sheet"
      description: "Allows you to delete a new sheet"
      operationId: "deleteSheetInfo"
      parameters:
      - name: "token"
        in: "header"
        description: "The user's session identifier"
        required: false
        type: "string"
        format: "string"
      - name: "sheetId"
        in: "path"
        description: "The product id we need to check inventory for"
        required: true
        type: "string"      
      responses:
        200:
          description: "A response describing status of the payment method update"
          schema:
            $ref: "#/definitions/TokenAcceptanceResponse"
        401:
          description: "Used for a 401 HTTP response - Client not authenticated"
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "The logged-in user is not permitted to perform the current\
            \ operation."
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Used for a 500 HTTP response - Internal server error"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Used for a 500 HTTP response - Internal server error"
          schema:
            $ref: "#/definitions/Error"
definitions:
  Error:  
    allOf:
    - type: "object"
      properties:
        code:
          type: "string"
          description: "Error code, if applicable"
        status:
          type: "integer"
          format: "int32"
          description: "HTTP status code"
    - $ref: "#/definitions/ApiResponse"
  ApiResponse:
    type: "object"
    required:
    - "timestamp"
    - "txnId"
    discriminator: "txnId"
    properties:
      txnId:
        type: "string"
        description: "Transaction ID"
      timestamp:
        type: "string"
        format: "date-time"
        description: "Timestamp of response"
      message:
        type: "string"
        description: "Human readable description of response"
  TokenAcceptanceResponse:
    allOf:
    - $ref: "#/definitions/TokenAcceptance"
    - $ref: "#/definitions/ApiResponse"
  TokenAcceptance:
    type: "object"
    properties:
      decision:
        type: "string"
        example: "ACCEPT"
        description: "Result of the overall request. Possible values: [ACCEPT, ERROR, REJECT]"
        enum:
        - "ACCEPT"
        - "ERROR"
        - "REJECT"
      reasonCode:
        type: "number"
        example: 123.0
        description: "Numeric value corresponding to the result of the request."
      reasonMessage:
        type: "string"
        example: "Something is wrong with token"
        description: "Text description to the reasonCode. Values are currently unknown."
    description: "The result of the operation obtained from update."
  InventoryResponse:
    type: "object"
    properties:
      productID:
          type: "string"
      merchant:
          type: "string"
      minimumInventory:
          type: "integer"
  SheetList:
    type: "object"
    properties:
      sheets:
        type: "array"
        items:
          $ref: "#/definitions/SheetInfo"
  SheetInfo:
    type: "object"
    properties:
      sheetId:
        type: "string"
      sheetName:
        type: "string"
      sheetDate:
        type: "string"
      sheetNotes:
        type: "string"
      active:
        type: "boolean"
  SheetDetails:
    type: "object"
    properties:
      sheetId:
        type: "string"
      sheetName:
        type: "string"
      sheetDate:
        type: "string"
      sheetNotes:
        type: "string"
      active:
        type: "boolean"
      updated:
        type: "string"
      updatedBy:
        type: "string"
      created:
        type: "string"
      createdBy:
        type: "string"
      data:
        type: "array"
        items:
           $ref: "#/definitions/SheetMetaData"
  SheetData:
    type: "object"
    properties:
      statements:
        type: "array"
        items:
          $ref: "#/definitions/SheetMetaData"
  SheetMetaData:
    type: "object"
    properties:
      rowId:
        type: "integer"
        format: "int32"
        description: "The unique resource identifier of the line associated with this row"
      inventory:
        type: "integer"
        format: "int32"
        description: "The total"
      title:
        type: "string"
        description: "The title"
      listingPrice:
        type: "number"
        format: "double"
        description: "The total"
      supplierName:
        type: "string"
        description: "The title"
      supplierPrice:
        type: "number"
        format: "double"
        description: "The total"
      listingFee:
        type: "number"
        format: "double"
        description: "The total"
      tax:
        type: "number"
        format: "double"
        description: "The total"
      shipping:
        type: "number"
        format: "double"
        description: "The total"
      profit:
        type: "number"
        format: "double"
        description: "The total"
      profitMargin:
        type: "number"
        format: "double"
        description: "The total"
      listingUrl:
        type: "string"
        description: "The title"
      supplierUrl:
        type: "string"
        description: "The title"
    description: "A line level breakdown of sheet items"
      
